// <auto-generated />
namespace HandIn2._2_Relation_Database.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MangeMange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MangeMange));
        
        string IMigrationMetadata.Id
        {
            get { return "201803230852582_MangeMange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
